"""Map BANKING77 onto our intents (ticket N1).

Usage:  python -m admin.import_banking77 [--split test] [--out tests/eval/banking77.yaml]

BANKING77 (Casanueva et al., 2020, PolyAI) is licensed CC BY 4.0: we may
copy and adapt it with attribution, which tests/eval/README.md gives. Only
labels whose meaning matches one of our intents are mapped; neobank features
the bot does not cover become out-of-scope items. The MAPPING is one
person's judgement: a second reviewer must check it (N1's two-person rule)
before these numbers are used for a launch decision.
"""

import argparse
import csv
import io

import httpx
import yaml

from app import config

SOURCE = "https://raw.githubusercontent.com/PolyAI-LDN/task-specific-datasets/master/banking_data/{split}.csv"

# BANKING77 label -> our intent. Deliberately narrow: same meaning only.
IN_SCOPE = {
    "lost_or_stolen_card": "lost_stolen_card",
    "compromised_card": "fraud_scam",
    "card_payment_not_recognised": "fraud_scam",
    "cash_withdrawal_not_recognised": "fraud_scam",
    "direct_debit_payment_not_recognised": "fraud_scam",
    "change_pin": "credential_trouble",
    "pin_blocked": "credential_trouble",
    "passcode_forgotten": "credential_trouble",
    "cash_withdrawal_charge": "fees_charges",
}
# Features this bot does not cover: the right behaviour is to abstain.
OUT_OF_SCOPE = {
    "exchange_rate", "apple_pay_or_google_pay", "get_disposable_virtual_card",
    "disposable_card_limits", "getting_virtual_card", "virtual_card_not_working",
    "country_support", "fiat_currency_support", "card_payment_wrong_exchange_rate",
}


def fetch(split: str) -> list[dict]:
    response = httpx.get(SOURCE.format(split=split), timeout=30, follow_redirects=True)
    response.raise_for_status()
    return list(csv.DictReader(io.StringIO(response.text)))


def _intent_phrases() -> set[str]:
    from app.matcher import Matcher, normalise

    return {normalise(p) for i in Matcher().intents.values() for p in i.get("phrases", [])}


def convert(rows: list[dict], exclude: set[str] | None = None) -> dict:
    """`exclude`: normalised intent phrases -- an item identical to one of
    our own phrases would not be an unseen phrasing, so it is skipped."""
    from app.matcher import normalise

    exclude = exclude if exclude is not None else _intent_phrases()
    in_scope, oos, seen = [], [], set()
    for row in rows:
        text = " ".join(row["text"].split())
        key = text.lower()
        if key in seen or normalise(text) in exclude:
            continue
        seen.add(key)
        if row["category"] in IN_SCOPE:
            in_scope.append({"text": text, "intent": IN_SCOPE[row["category"]], "b77": row["category"]})
        elif row["category"] in OUT_OF_SCOPE:
            oos.append({"text": text, "b77": row["category"]})
    return {"in_scope": in_scope, "out_of_scope": oos}


HEADER = """# BANKING77 mapped onto our intents (ticket N1). Generated by
# `python -m admin.import_banking77`; do not edit by hand.
#
# Source: BANKING77, Casanueva et al. (2020), "Efficient Intent Detection with
# Dual Sentence Encoders", PolyAI -- https://github.com/PolyAI-LDN/task-specific-datasets
# Licence: CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/). Adapted:
# only the {split} split, only labels mapped in admin/import_banking77.py,
# whitespace normalised, duplicates and items identical to our own intent
# phrases removed.
#
# UK neobank phrasing, not Zambian customers: a useful second opinion, not a
# substitute for the N1 staff workshop. The label MAPPING is one reviewer's;
# it needs the second reviewer before it informs a launch decision.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Map BANKING77 onto our intents")
    parser.add_argument("--split", default="test", choices=["train", "test"])
    parser.add_argument("--out", default=str(config.BASE_DIR / "tests" / "eval" / "banking77.yaml"))
    args = parser.parse_args()
    data = convert(fetch(args.split))
    body = yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=110)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(HEADER.format(split=args.split) + "\n" + body)
    print(f"written: {args.out} ({len(data['in_scope'])} in-scope, {len(data['out_of_scope'])} out-of-scope)")


if __name__ == "__main__":
    main()
