"""Export every launch intent to one reviewable markdown file for legal.

Usage:  python -m admin.legal_export  [--out docs/intent-review.md]

Build plan §10: "Draft the ~25 launch intents + answers and get them in
front of legal early." Regenerate after every content edit.
"""

import argparse
import datetime as dt
import re
from pathlib import Path

import yaml

from app import config

CONFIRM_RE = re.compile(r"\[CONFIRM[^\]]*\]")


def build_doc() -> str:
    sections = []
    confirms = []
    total = 0
    for path in sorted(config.INTENTS_DIR.glob("*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        intents = data.get("intents", [])
        sections.append(f"\n## {path.stem} ({len(intents)} intents)\n")
        for item in intents:
            total += 1
            sections.append(f"### {item['label']}  `{item['intent']}`\n")
            sections.append(f"- Status: **{item.get('status', 'draft')}**")
            if item.get("flow"):
                sections.append(
                    f"- Starts the structured `{item['flow']}` flow — scripted "
                    f"prompts live in `app/flows/{item['flow']}.py` (review those too)"
                )
            phrases = item.get("phrases", [])
            sections.append(
                f"- Trigger phrases ({len(phrases)}): "
                + ", ".join(f'"{p}"' for p in phrases)
            )
            answer = (item.get("answer") or "").strip()
            if answer:
                for hit in CONFIRM_RE.findall(answer):
                    confirms.append((item["intent"], hit))
                sections.append("\nCustomer-facing answer:\n")
                sections.append("> " + answer.replace("\n", "\n> "))
            buttons = item.get("buttons", [])
            if buttons:
                sections.append(
                    "\nFollow-up buttons: " + " · ".join(b["label"] for b in buttons)
                )
            sections.append("")

    header = [
        "# AB Bank Zambia chatbot — V1 launch intents for legal review",
        "",
        f"Generated {dt.date.today().isoformat()} from `knowledge/intents/*.yaml`.",
        "Regenerate with `python -m admin.legal_export`. Do not edit this file by",
        "hand — edit the YAML and regenerate.",
        "",
        f"**{total} intents. ALL ANSWERS ARE DRAFTS** — nothing launches until "
        "every item below is signed off (build plan §3.5) and every "
        "`[CONFIRM …]` placeholder is resolved.",
        "",
        "## Outstanding [CONFIRM] items in answers",
        "",
    ]
    if confirms:
        header += [f"- `{intent}`: {hit}" for intent, hit in confirms]
    else:
        header.append("None — all placeholders resolved.")
    header.append(
        "\nAlso confirm the contact values in `app/config.py` CONTACTS: "
        + ", ".join(
            f"{key}={value}" for key, value in config.CONTACTS.items()
            if str(value).startswith("[CONFIRM")
        )
    )
    return "\n".join(header) + "\n" + "\n".join(sections) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Export intents for legal review")
    parser.add_argument(
        "--out", type=Path, default=config.BASE_DIR / "docs" / "intent-review.md"
    )
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_doc(), encoding="utf-8")
    print(f"written: {args.out}")


if __name__ == "__main__":
    main()
